---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define groonga_repo_url.
  set_fact:
    groonga_repo_url: "{{ __groonga_repo_url }}"
  when: groonga_repo_url is not defined

- name: Define mecab_enable_repo.
  set_fact:
    mecab_enable_repo: "{{ __mecab_enable_repo }}"
  when: mecab_enable_repo is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'